apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: service
  name: gubernator-rolebinding-tds
subjects:
- kind: ServiceAccount
  name: telematics-data-source-api
  namespace: service
roleRef:
  kind: Role
  name: gubernator-role
  apiGroup: rbac.authorization.k8s.io
